apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: metallb
    name: metallb
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb
spec:
  finalizers:
  - kubernetes
