apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
  namespace: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/storage
allowedTopologies:
  - matchLabelExpressions:
      - key: storage
        values:
          - ssd
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer